name: Build and Test C++ Drogon App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt update apt install
          sudo apt install -y cmake build-essential libdrogon-dev

      - name: Configure and Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      # - name: Run Tests
      #   run: |
      #     cd build
      #     ./BankAppTests # если у вас есть отдельный файл с тестами
