name: Docker Build and Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Скачиваем код
      - name: Checkout code
        uses: actions/checkout@v2

      # Сборка Docker-образа
      - name: Build Docker Image
        run: docker build -t myapp:latest .

      # Запуск Docker-контейнера
      - name: Run Docker Container
        run: docker run -d -p 8848:8848 --name myapp myapp:latest

      # Проверка, что сервис запущен
      - name: Wait for service to start
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:8848; then
              echo "Service is up!"
              exit 0
            fi
            echo "Waiting for service..."
            sleep 5
          done
          echo "Service did not start in time" && exit 1

      # Запуск тестов
      - name: Run tests
        run: docker exec myapp /bin/bash -c "cd ./build && ctest"

      # Остановка и удаление контейнера после теста
      - name: Stop and remove Docker Container
        if: always()
        run: docker rm -f myapp
